version: 2
project_name: jenkinsmaster

builds:
  - id: jenkinsmaster
    main: ./main.go
    binary: jenkinsmaster
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

release:
  github:
    owner: mamrezb
    name: jenkinsmaster-cli

brews:
  - name: jenkinsmaster
    repository:
      owner: mamrezb
      name: homebrew-jenkinsmaster-cli
    description: "A CLI tool to manage Jenkins master"
    commit_author:
      name: mamrezb
      email: behfar.mr@gmail.com
    goarm: 7
    homepage: https://github.com/mamrezb/jenkinsmaster-cli
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |-
      bin.install "{{ .ArtifactName }}" => "{{ .ProjectName }}"
    dependencies:
      - git
